---
nocite: | 
  # PARTE I -- FUNDAMENTAÇÃO HISTÓRICA E CONCEITUAL
  
  # Pedologia Quantitativa (ou Pedometria)
  @Heuvelink2003c, @Heuvelink2003b, @Heuvelink2003a,
  @Jenny1941,
  @McBratney2003, @McBratneyEtAl2000,
  @Webster1994, @Wittgenstein1999,
  
  # Mapeamento Digital do Solo
  @BurroughEtAl1994,
  @HenglEtAl2007a, @Heuvelink2003a,
  @LagacherieEtAl2007a,
  @McBratneyEtAl2003,
  @Samuel-RosaEtAl2015,
  @Troeh1964,
  
  # PARTE III -- AMOSTRAGEM ESPACIAL
  
  # Princípios da Amostragem Espacial
  @deGruijterEtAl2006,
  @Mueller2007,
  @WebsterEtAl2013,
  
  # Amostragem Probabilística
  @deGruijterEtAl2006,
  
  # Amostragem Não-Probabilística
  @BrusEtAl2007a,
  @Rossiter2000,
  @Samuel-Rosa2012,
  @WebsterEtAl1990,
  
  # PARTE V -- ANÁLISE EXPLORATÓRIA ESPACIAL
  
  # Tipos de Dados
  @HairEtAl2010, @HenglEtAl2007a,
  @WebsterEtAl1990,
  
  # PARTE VI -- MODELAGEM DA VARIAÇÃO ESPACIAL (I)

  # O Componente Determinístico

  # Regressão Linear
  @DiggleEtAl2007,
  @Heuvelink1996, @HeuvelinkEtAl2001,
  @KutnerEtAl2004,
  @NussbaumEtAl2014,
  @Papritz2015,
  
  # Regressão Logística
  @Agresti2002
  
  # PARTE VII -- MODELAGEM DA VARIAÇÃO ESPACIAL (II)
  
  # O Componente Estocástico
  @Everitt2006, 
  @Florinsky2012,
  @Jenny1941,
  @Kuhn2011,
  @McBratneyEtAl2003,
  @Webster1994

...
