<!-- # PARTE II -- INFRAESTRUTURA TECNOLÓGICA {-} -->

<!-- # Hardware -->

<!-- # Software -->

# Gestão de Dados

**Atenção!** Este capítulo está em fase de *desenvolvimento*. Visite a [página do projeto][issues] se tiver 
alguma sugestão, dúvida ou estiver disposto a colaborar. Sua opinião/ajuda é muito importante!

## Introdução

Um importante passo consiste na criação do nosso diretório de trabalho. Para isso, acesse seu gerenciador
de diretórios e crie a seguinte estrutura de diretórios em seu local favorito de trabalho:

    projeto
    |- code/       # qualquer código de programação
    |  |- R/       # código de programação em R
    |
    |- data
    |  |- grid/    # dados matriciais
    |  |- R/       # dados no formato *.rda
    |  |- vector/  # dados vetoriais
    |
    |- doc/        # arquivos usados para redigir o relatório
    |  |- fig/     # figuras usadas no relatório

Note que, dentro do nosso diretório de trabalho principal (`projeto`) existem três subdiretórios:
`code`, `data` e `doc`. O primeiro deles, `code`, serve para armazernamos os arquivos
contendo código de programação em qualquer linguagem. Para cada linguagem criamos um subsubdiretório 
específico. Nesse exemplo, como usaremos apenas o R, criaremos apenas um subsubdiretório chamado R. Ali 
dentro serão armazenados os *scripts* com código de programação do escritos em R.

O segundo subdiretório será utilizado para armazenarmos os dados usados no projeto. Nesse exemplo, são 
três os tipos de dados que utilizaremos, cada um armazenado em um subsubdiretório específico. No 
subsubdiretório `grid` ficarão armazenados os dados matriciais, ou seja, os dados das covariáveis e 
os resultados das predições espaciais. Já no subsubdiretório `vector` ficarão armazenados os dados 
vetoriais, ou seja, aqueles cuja forma de representação espacial pode ser a de pontos, linhas e polígonos. 
Isso inclui os dados de solo e dos limites da área de estudo. Por fim, o subsubdiretório R será
usado para armazenar dados diversos produzidos durante o processamento no R, os quais serão salvos 
usando o formato `rda`.

O terceito e último subdiretório de nosso diretório de trabalho `projeto`, aqui denominado `doc`,
será usado para armazenar os arquivos usados para redigir os documentos resultantes do projeto.

No RStudio, acesse

    Arquivo > Novo projeto > Diretório existente

e navegue até o diretório recém criado `projeto`. Clique em `Criar projeto`. Toda a 
estrutura de diretórios criada recentemente aparecerá no painel direito inferior do RStudio. Agora crie um
novo arquivo do R e salve-o no diretório `bigdata > code > R`. Será nesse arquivo que você organizará o 
código em R usado para o processamento dos dados. A criação de um projeto no RStudio 
facilita a organização dos dados.
Sempre que uma rotina de análises for desenvolvida no R é preciso definir o diretório de trabalho. O diretório 
de trabalho constitui a pasta em que estão localizados os arquivos contendo os dados a serem analisados. Além 
disso, é no diretório de trabalho que o R salva o histórico de trabalho contendo todas as operações realizadas.

Inicie o QGIS e acesse

    Projeto > Novo > Salvar como

e navegue até o diretório `projeto`. Nomeie o projeto como `projeto`. Assim como para o
RStudio, a criação de um projeto no QGIS facilita a organização dos dados.

## Bases de Dados do Solo

### Perfis do Solo

* CENA-USP: Digital soil properties database of the Amazon part from the RADAMBRASIL project
    + ftp://fapespclima.ccst.inpe.br/lba/ornlworking/carbon_dynamics/CD/CD-208/CD208_RADAMBRASIL_Soils/
* Esalq-USP: A national soil profile database for Brazil available to international scientists
    + http://www.esalq.usp.br/gerd/
* EMBRAPA: Sistema de Informação de Solos Brasileiros
    + https://www.bdsolos.cnptia.embrapa.br/consulta_publica.html
* ISRIC: World Soil Information Service (WoSIS)
    + http://www.isric.org/data/wosis
* NASA: Large-Scale Biosphere-Atmosphere Experiment in Amazonia
    + https://daac.ornl.gov/LBA/lba.shtml

### Mapas do Solo 

* EMBRAPA: GeoPortal Digital
  + http://mapoteca.cnps.embrapa.br/
* ISRIC: SoilGrids
  + https://soilgrids.org/
