<!-- # PARTE III -- AMOSTRAGEM ESPACIAL {-} -->

<!-- # Princípios da Amostragem Espacial -->

# Amostragem Probabilística

**Atenção!** Este capítulo está em fase de *desenvolvimento*. Visite a [página do projeto][issues] se tiver 
alguma sugestão, dúvida ou estiver disposto a colaborar. Sua opinião/ajuda é muito importante!

## Introdução

A característica fundamental da amostragem probabilística é que a chance de um determinado local ser amostrado
(probabilidade de inclusão) é conhecida e maior do que zero. Em outras palavras, todo e qualquer local possui 
alguma chance de ser amostrado, mesmo que alguns tenham maior chance do que outros. Um local que não pode ser 
amostrado tem probabilidade de inclusão igual a zero.

A amostragem probabilística é muito utilizada em experimentos controlados, como aqueles desenvolvidos em 
campos experimentais, casas de vegetação e laboratórios. No caso da modelagem espacial do solo, a amostragem
probabilística costuma ser usada para a validação das predições espaciais. Entretanto, ela também pode ser 
usada para obter observações para a calibração dos modelos preditivos.

<!-- # Amostragem Não-Probabilística -->
