--- 
title: "Pedologia Quantitativa feita Simples"
author: "Alessandro Samuel-Rosa"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib, ~/Dropbox/jabref/biblio.bib]
csl: abnt.csl
# biblio-style: apalike
link-citations: yes
github-repo: samuel-rosa/pedologia-quantitativa
---

# Prefácio {-}

O planejamento e desenvolvimento deste livro estão (mais ou menos) estruturados em partes, de 
caráter mais geral, subdivididas em capítulos, de caráter mais específico. Atualmente, isso se dá da seguinte
maneira:

* Parte I -- Fundamentação histórica e conceitual
    + Contextualização histórica
    + Pedologia quantitativa (ou pedometria)
    + Mapeamento digital do solo
* Parte II -- Infraestrutura tecnológica
    + Hardware
    + Software
    + Gestão de dados
* Parte III -- Amostragem espacial
    + Princípios da amostragem espacial
    + Amostragem probabilística
    + Amostragem não-probabilística
* Parte IV -- Covariáveis ambientais
    + Princípios da formação do solo
    + Modelos digitais de elevação
    + Imagens de satélite
* Parte V -- Análise exploratória espacial
    + Tipos de dados
    + Análise de padrões pontuais
    + Transformação de dados
    + Seleção de covariáveis
* Parte VI -- Modelagem da variação espacial (I)
    + O componente determinístico
    + Regressão linear
    + Regressão logística
* Parte VII -- Modelagem da variação espacial (II)
    + O componente estocástico
    + Geoestatística univariada
    + Geoestatística multivariada

[issues]: https://github.com/samuel-rosa/pedologia-quantitativa/issues "Sugestões e dúvidas"
